name: "Scrape and Build"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.scrapejob.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        working-directory: ./scripts
      - id: scrapejob
        run: npm run scrape
        working-directory: ./scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: scrape
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ${{ fromJSON(needs.scrape.outputs.result) }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ fromJSON(matrix.job).source.owner }}/${{ fromJSON(matrix.job).source.repository }}
          ref: ${{ fromJSON(matrix.job).source.tag }}
          path: ${{ fromJSON(matrix.job).source.repository }}
      - uses: actions/checkout@v3
        with:
          path: stocker
      # - idempotently create the image repository and update the readme
      - uses: docker/build-push-action@v2
        with:
          context: ${{ fromJSON(matrix.job).source.repository }}
          file: stocker/repositories/${{ fromJSON(matrix.job).image.repository }}/Dockerfile
          push: true
          tags: stocker/${{ fromJSON(matrix.job).image.repository }}:${{ fromJSON(matrix.job).image.tag }}
      - run: >
          cat <<- EOF > stocker/${{ fromJSON(matrix.job).image.repository }}/${{ fromJSON(matrix.job).image.tag }}
            Successfully built and pushed stocker/${{ fromJSON(matrix.job).image.repository }}:${{ fromJSON(matrix.job).image.tag }}
          EOF
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Complete build stocker/${{ fromJSON(matrix.job).image.repository }}:${{ fromJSON(matrix.job).image.tag }}"
          commit_options: "--no-signoff"
          file_pattern: stocker/${{ fromJSON(matrix.job).image.repository }}/${{ fromJSON(matrix.job).image.tag }}
          repository: stocker
          branch: main
